# Generated by Django 4.1 on 2022-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
